name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
        role-session-name: GitHubActions
        aws-region: us-east-1

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

    # Build, tag, and push Docker image
    - name: Build, Tag & Push Docker Image for Hello World Service
      run: |
        docker build -t nodejs-api-lambda ./backend
        docker tag nodejs-api-lambda:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nodejs-api-repo:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nodejs-api-repo:latest

    # Cleanup local Docker images
    - name: Cleanup local Docker images
      run: docker image prune -af
